# Generated by Django 3.2.6 on 2021-08-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='email_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
